import type {
  AchievementDef,
  FamiliarDef,
  NoteDef,
  RankDef,
  SpiritDef,
  TechniqueDef,
} from "./types";

export const APP_NAME = "5t5：无限";
export const SAVE_KEY = "stst-limitless-save-v1";
export const SAVE_VERSION = 2;

export const TECHNIQUES: TechniqueDef[] = [
  {
    id: "sense",
    name: "咒力感知",
    kana: "基础",
    desc: "重新摸到咒力的边。每级提高自动产出。",
    kind: "prod",
    baseCost: 12,
    costMult: 1.14,
    prod: 0.4,
    unlockAt: 0,
  },
  {
    id: "limitless",
    name: "无极术式",
    kana: "无穷",
    desc: "把空间叠进无限。靠近的秽物会先被摊平。",
    kind: "prod",
    baseCost: 80,
    costMult: 1.15,
    prod: 2.2,
    unlockAt: 40,
  },
  {
    id: "blue",
    name: "苍 · 引力",
    kana: "术式顺转",
    desc: "把世界往一点吸。购买后可主动释放，把当前秽物往里折。",
    kind: "prod",
    baseCost: 420,
    costMult: 1.15,
    prod: 11,
    unlockAt: 250,
  },
  {
    id: "red",
    name: "赫 · 斥力",
    kana: "术式反转",
    desc: "正向咒力的反面。购买后可主动轰开当前目标。",
    kind: "prod",
    baseCost: 2_400,
    costMult: 1.16,
    prod: 48,
    unlockAt: 1_600,
  },
  {
    id: "eyes",
    name: "六瞳",
    kana: "天与",
    desc: "看清咒力的纹理。降低术式成本，并提高全局倍率。",
    kind: "eyes",
    baseCost: 9_000,
    costMult: 1.18,
    prod: 0,
    unlockAt: 6_000,
  },
  {
    id: "purple",
    name: "虚式 · 紫",
    kana: "虚构",
    desc: "引力与斥力对撞后的虚构质量。购买后可主动抹除。",
    kind: "prod",
    baseCost: 5.5e4,
    costMult: 1.17,
    prod: 260,
    unlockAt: 3e4,
  },
  {
    id: "rct",
    name: "逆转术式",
    kana: "再生",
    desc: "用正的咒力修补自己。大幅提高每次点按产出。",
    kind: "click",
    baseCost: 2.8e5,
    costMult: 1.16,
    prod: 0,
    unlockAt: 1.2e5,
  },
  {
    id: "flash",
    name: "黑闪",
    kana: "时空",
    desc: "咒力在空间里滞后 0.000001 秒。暴击率与暴击伤害上升。",
    kind: "crit",
    baseCost: 1.6e6,
    costMult: 1.2,
    prod: 0,
    unlockAt: 6e5,
  },
  {
    id: "simple",
    name: "简易结界",
    kana: "防",
    desc: "一掌半径的结界。给自动除灵提供稳定输出。",
    kind: "prod",
    baseCost: 9e6,
    costMult: 1.17,
    prod: 1_800,
    unlockAt: 4e6,
  },
  {
    id: "domain",
    name: "术域 · 无量空域",
    kana: "必中",
    desc: "展开一次。域内的信息量把对方钉死。主动技：短时爆发。",
    kind: "domain",
    baseCost: 6e7,
    costMult: 1.22,
    prod: 1.2e4,
    unlockAt: 2.5e7,
  },
];

export const FAMILIARS: FamiliarDef[] = [
  {
    id: "first-year",
    name: "见习咒术师",
    desc: "刚会握咒具的小孩。点击之余替你扫四级秽物。",
    baseCost: 60,
    costMult: 1.13,
    prod: 0.8,
    unlockAt: 25,
  },
  {
    id: "craftsman",
    name: "咒具工匠",
    desc: "连夜打刃。每一口铁都喂进无极。",
    baseCost: 750,
    costMult: 1.14,
    prod: 7,
    unlockAt: 400,
  },
  {
    id: "shikigami",
    name: "式神群",
    desc: "纸与影子编成的猎队。不睡觉。",
    baseCost: 8_800,
    costMult: 1.15,
    prod: 55,
    unlockAt: 5_000,
  },
  {
    id: "watcher",
    name: "夜视监视员",
    desc: "不战斗，只报点。让你少走空。",
    baseCost: 9.5e4,
    costMult: 1.15,
    prod: 380,
    unlockAt: 4e4,
  },
  {
    id: "clone",
    name: "残影分身",
    desc: "无极里撕下来的残像。会替你按。",
    baseCost: 1.2e6,
    costMult: 1.16,
    prod: 2_600,
    unlockAt: 4e5,
  },
  {
    id: "engine",
    name: "无限演算",
    desc: "六瞳把世界算成一条河。河自己会流。",
    baseCost: 1.8e7,
    costMult: 1.18,
    prod: 2.2e4,
    unlockAt: 6e6,
  },
];

export const SPIRITS: SpiritDef[] = [
  {
    id: "fly",
    name: "蝇头",
    grade: "四级",
    flavor: "走廊尽头那点嗡鸣。",
    art: "/art/spirit-fly.png",
    baseHp: 18,
    reward: 14,
    minWave: 0,
  },
  {
    id: "fetal",
    name: "胎怨",
    grade: "三级",
    flavor: "还没出生就已经会恨。",
    art: "/art/spirit-fetal.png",
    baseHp: 90,
    reward: 70,
    minWave: 6,
  },
  {
    id: "mouth",
    name: "众口",
    grade: "二级",
    flavor: "每一张嘴都在学人说话。",
    art: "/art/spirit-mouth.png",
    baseHp: 420,
    reward: 320,
    minWave: 14,
  },
  {
    id: "blood",
    name: "血涂",
    grade: "一级",
    flavor: "屠宰场自己站了起来。",
    art: "/art/spirit-blood.png",
    baseHp: 2_200,
    reward: 1_800,
    minWave: 24,
  },
  {
    id: "disaster",
    name: "灾核",
    grade: "特级",
    flavor: "城市下面那口还在跳的心脏。",
    art: "/art/spirit-disaster.png",
    baseHp: 1.4e4,
    reward: 1.2e4,
    minWave: 40,
  },
];

export const RANKS: RankDef[] = [
  { id: "g4", name: "四级", lifetime: 0, mult: 1 },
  { id: "g3", name: "三级", lifetime: 800, mult: 1.05 },
  { id: "g2", name: "二级", lifetime: 6_000, mult: 1.1 },
  { id: "g1", name: "一级", lifetime: 4e4, mult: 1.18 },
  { id: "semi", name: "准特级", lifetime: 2.5e5, mult: 1.28 },
  { id: "special", name: "特级", lifetime: 1.5e6, mult: 1.42 },
  { id: "calamity", name: "灾级", lifetime: 1.2e7, mult: 1.6 },
  { id: "strongest", name: "最强", lifetime: 8e7, mult: 2 },
];

export const ACHIEVEMENTS: AchievementDef[] = [
  { id: "first-click", name: "第一指", desc: "重新摸到咒力。" },
  { id: "first-kill", name: "除灵", desc: "祓除第一只秽物。" },
  { id: "flash", name: "黑闪", desc: "咒力在空间里迟到。" },
  { id: "combo20", name: "连击二十", desc: "不要停。" },
  { id: "domain", name: "展开", desc: "第一次术域。" },
  { id: "special", name: "特级", desc: "阶位抵达特级。" },
  { id: "prestige", name: "再开", desc: "把一切清零，只留下最强。" },
  { id: "k100", name: "百斩", desc: "祓除一百只秽物。" },
  { id: "blue", name: "苍", desc: "第一次主动释放术式顺转。" },
  { id: "purple", name: "虚式", desc: "虚构质量过境。" },
  { id: "boss", name: "遭遇", desc: "解决一次十波一遇。" },
];

export const NOTES: NoteDef[] = [
  {
    id: "n-g4",
    rankId: "g4",
    title: "狱门之后",
    body: "咒力被抽空的感觉很无聊。从四级重新数，也好。至少这次没人在旁边吵。",
  },
  {
    id: "n-g3",
    rankId: "g3",
    title: "走廊",
    body: "蝇头一类的东西不值得六瞳。不过手还记得怎么比划。",
  },
  {
    id: "n-g2",
    rankId: "g2",
    title: "无极",
    body: "靠近就会被摊平。他们总把这叫温柔。我只是懒得被碰到。",
  },
  {
    id: "n-g1",
    rankId: "g1",
    title: "苍与赫",
    body: "一拉一推。世界比人老实，数字对得上就会塌。",
  },
  {
    id: "n-semi",
    rankId: "semi",
    title: "六瞳",
    body: "咒力的纹理又清楚了。贵的不是眼睛，是看完还愿意动手。",
  },
  {
    id: "n-special",
    rankId: "special",
    title: "特级",
    body: "这一档开始有点意思。别眨眼。",
  },
  {
    id: "n-calamity",
    rankId: "calamity",
    title: "灾",
    body: "城市下面那口心脏还在跳。那就把它按回去。",
  },
  {
    id: "n-strongest",
    rankId: "strongest",
    title: "最强",
    body: "又一次。吾乃最强。这次不进门。",
  },
];

export const LINES = [
  "吾乃最强。",
  "别眨眼。",
  "无极之内，碰不到我。",
  "就这？",
  "咒力……再多一点。",
  "你以为距离是线性的？",
  "看清楚了再打。",
  "域，要开了。",
  "苍。",
  "赫。",
  "虚式。",
];

export const PRESTIGE_AT = 4e5;
export const DOMAIN_DURATION = 10_000;
export const DOMAIN_COOLDOWN = 70_000;
export const SKILL_CD = {
  blue: 8_000,
  red: 14_000,
  purple: 24_000,
} as const;
export const OFFLINE_CAP_MS = 8 * 60 * 60 * 1000;
export const OFFLINE_RATE = 0.55;
